# Generated by Django 3.1.4 on 2021-03-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='user',
        ),
    ]
