# Generated by Django 3.1.4 on 2021-03-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_remove_quest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='approved',
        ),
        migrations.AlterField(
            model_name='quest',
            name='type',
            field=models.CharField(choices=[('NK', 'Konferencje'), ('NA', 'Artykuły'), ('ND', 'Debaty'), ('NB', 'Badania'), ('NS', 'Specjaliści'), ('EA', 'Średnia'), ('ES', 'Semestry'), ('EO', 'Obowiązki Pierwszaka'), ('ET', 'Szkolenia'), ('EP', 'Staże'), ('EC', 'Certyfikaty'), ('EB', 'Bierny udział'), ('EW', 'Wyjazdy edukacyjne'), ('E', 'Specjalne'), ('EE', 'Specjaliści'), ('OO', 'Organizacje Studenckie'), ('OW', 'Wydarzenia'), ('OP', 'Praca podczas studiów'), ('OE', 'Specjalne'), ('OS', 'Specjaliści'), ('FW', 'Wyjazdy'), ('FI', 'Imprezy integracyjne'), ('FA', 'Absurdy'), ('FJ', 'Juvenalia'), ('FS', 'Specjaliści')], max_length=2),
        ),
    ]
