# Generated by Django 3.1.4 on 2021-03-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20201207_2041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nagroda',
        ),
    ]
